spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weather_app
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
