spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weather_app
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update


  weather:
    api:
      key: "J28I%2B2X%2FLQ8vHJaw2Yorr492RFOq2%2FRBGCkl1hVMJCu65fNG5xDvDi7GazJpx3ZKa9xb4fYhq14vtXjWSaHrSw%3D%3D"
      url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
  jwt:
    expiration_time: 86400000 #1일
    secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs
